Connected to api
tayor99/Blog pull request #3
Opened 2022-06-03 15:51 UTC by tayor99

I connect to the bright's api and edited the previous changes

2022-06-03 19:55 UTC, Asylcreek requested changes

2022-06-03 19:55 UTC, Asylcreek commented on tayo-blog/src/Pages/Home.js
> +
Why save this into a variable?

2022-06-03 19:55 UTC, Asylcreek commented on tayo-blog/src/Pages/Home.js
> +    };
No error handling?

2022-06-03 19:55 UTC, Asylcreek commented on tayo-blog/src/Pages/Newpost.js
> +    axios.post(
I believe you are supposed to `await` this

2022-06-03 19:55 UTC, Asylcreek commented on tayo-blog/src/Pages/Newpost.js
> +  const [content, setContent] = useState('');
You can put each of these into one state item, like so
```jsx
const [newPost, setNewPost] = useState({name:"",title:"",content:""})
```

2022-06-05 01:27 UTC, tayor99 commented on tayo-blog/src/Pages/Home.js
> +
I wanted to make my code more readable

2022-06-06 10:07 UTC, Asylcreek commented on tayo-blog/src/Pages/Home.js
> +
Okay

2022-07-21 18:31 UTC, merged